---
- name: sleep 10s
  command: sleep 10s

- name: setup dabatase on influxdb
  shell: "curl -X POST 'http://localhost:8086/db?u={{ influxdb.username}}&p={{ influxdb.password }}' -d '{\"name\": \"{{ influxdb.dbname }}\"}'"
