---
- name: setup public signing key of yum repository for elasticsearch
  rpm_key: key=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: setup yum repository of elasticsearch
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo owner=root group=root mode=0644
  notify: yum update
